-------PROFILES-------
create table public.profiles (
    id uuid not null references auth.users on delete cascade,
	created_at bigint, 
	updated_at bigint, 
    first_name text,
	last_name text,
    email text,
	photo_url text,
    primary key (id)
);
-------RESOURCES-------
create table public.resources (
    id bigint generated by default as identity primary key,
	resource_table_id bigint,
	ref_table text,
	level int,
	hierarchy jsonb
);
-------COMPANIES-------
create table public.companies (
    id bigint generated by default as identity primary key,
    created_at bigint, 
	updated_at bigint, 
    resource_id bigint not null references resources (id) on delete cascade,
	name text, 
	description text
);
-------UNITS-------
create table public.units(
    id bigint generated by default as identity primary key,
    created_at bigint, 
	updated_at bigint, 
    resource_id bigint not null references resources (id) on delete cascade,
	name text, 
	description text
);
-------DEPARTAMENTS-------
create table public.departaments(
    id bigint generated by default as identity primary key,
    created_at bigint, 
	updated_at bigint, 
    resource_id bigint not null references resources (id) on delete cascade,
	name text,
	description text
);
-------PERMISSIONS-------
create table public.permissions (
    id bigint generated by default as identity primary key,
    created_at bigint, 
	updated_at bigint, 
	user_id uuid not null references profiles (id) on delete cascade,
    resource_id bigint not null references resources (id) on delete cascade,
	role varchar(20),
);

